### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ktun95** [dictybase-playground/image-component-demo#1]
- [x] Add documentation
- [x] single object for width and height state
- [ ] testing
- [ ] group image component properties
- [x] use number for width / height parameters
- [ ] styling / animation for resize elements
- [x] refactor Resizer
- [ ] using transform to position resize elements
